function NetworkInspector(MainFig)

h = figure('Units','pixels',...
			'Position',[150 100 700 450],...
			'Resize','off',...
			'NumberTitle','off',...
			'Menubar','none',...
			'Toolbar','none',...
			'Name','Network Inspector',...
            'CloseRequestFcn',@Close);

handles.MainFig = MainFig;
